Random Projection (SimHash) 
First proposed [here](https://www.cs.princeton.edu/courses/archive/spr04/cos598B/bib/CharikarEstim.pdf)

In [1]:
import gensim.downloader as api
import numpy as np

In [2]:
dim = 300

In [3]:
embeddings = api.load(f'word2vec-google-news-{dim}')

In [5]:
def knn(v, embeddings, k):
    # cosine similarity between v and all embeddings
    similarity = np.dot(embeddings,v)/(np.linalg.norm(embeddings,axis=1)*np.linalg.norm(v))    
    # get top k indices
    indices = np.argpartition(similarity, -k)[-k:]
    
    return indices
    

In [6]:
indices = knn(embeddings.get_vector('man'), embeddings.vectors, 3)
[embeddings.index2word[index.item()] for index in indices]

['boy', 'woman', 'man']

In [7]:
u = embeddings.get_vector('Athens')
v = embeddings.get_vector('Greece')

w = embeddings.get_vector('Jerusalem')
#p = ?
# p-w=v-u -> p=v-u+w

In [8]:
u = embeddings.get_vector('man')
v = embeddings.get_vector('king')

w = embeddings.get_vector('woman')
#p = ?
# p-w=v-u -> p=v-u+w

In [9]:
indices = knn(v-u+w, embeddings.vectors, 3)
[embeddings.index2word[index.item()] for index in indices]

['monarch', 'queen', 'king']

In [10]:
# create n hyperplanes
n_planes = 10
hyperplanes = np.random.normal(size=(n_planes,dim))

In [11]:
hyperplanes.shape

(10, 300)

In [13]:
np.dot(hyperplanes,v) >= 0

array([ True, False,  True,  True, False,  True,  True, False,  True,
       False])

In [14]:
np.array([1,2,3]).shape

(3,)

In [17]:
np.packbits(x)

array([188, 128], dtype=uint8)

In [16]:
x = np.array([ True, False,  True,  True,  True,  True, False, False,True])

In [27]:
# https://stackoverflow.com/questions/60118227/python-fastest-way-of-packing-a-2d-array-of-binary-values-into-uint64-array
np.packbits(x).astype(np.uint32).view(np.uint64)


array([549755814076], dtype=uint64)

In [24]:
test = (np.dot(hyperplanes,v) >= 0).astype(np.uint32)

In [236]:
(np.dot(hyperplanes,v) >= 0).astype(np.uint32)

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0], dtype=uint32)

In [28]:
foldl

NameError: name 'foldl' is not defined